version: '3.3'
services:
services:
  servicio1:
    container_name: servicio1
    image: servicio1
    build: 
      dockerfile: Dockerfile 
      context: ./servicio1
    environment: 
      - HOST=mysql-bd      
    ports:
      - '3003:3003'
    depends_on:
      - mysql-bd
  servicio2:
    container_name: servicio2
    image: servicio2
    build: 
      dockerfile: Dockerfile 
      context: ./servicio2
    environment: 
      - HOST=mysql-bd      
    ports:
      - '4003:4003'
    depends_on:
      - mysql-bd
  mysql-bd:
    container_name: mysql-bd
    image: mysql-bd
    build: 
      dockerfile: Dockerfile
      context: ./mysql-bd
    ports: 
      - '33060:3306'
  servicio3:
    container_name: servicio3
    image: servicio3
    build: 
      dockerfile: Dockerfile 
      context: ./servicio3
    environment: 
      - HOST=mysql-bd      
    ports:
      - '5003:5003'
    depends_on:
      - mysql-bd

