apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: servicio4
  name: servicio4
spec:
  ports:
    - name: "6003"
      port: 6003
      targetPort: 6003
  selector:
    io.kompose.service: servicio4
status:
  loadBalancer: {}
