apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: servicio8
  name: servicio8
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: servicio8
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: servicio8
    spec:
      containers:
        - env:
            - name: HOST
              value: mysql-bd
          image: gcr.io/aerial-anagram-300108/servicio8
          name: servicio8
          ports:
            - containerPort: 9009
          resources: {}
      restartPolicy: Always
status: {}
