---
- hosts: localhost

  tasks:
    - name: Install npm
      apt:
       name: npm
       state: present
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Install node
      apt:
        name : nodejs
        state: present

    - name: update
      yum:
        name: "*"
        state: latest

    - name: installing java
      apt:
        name: default-jre
        state: present

    - name: installing jdk
      apt:
        name: default-jdk
        state: present
        
    - name: saluda
      shell: echo hola